### ISSUE TITLE
Support nginx proxy forwarding dashboard

### ISSUE THREAD

**Issue by mg0324** [emqx/emqx-dashboard#15]
Can add configuration items · `dashboard.listener.http.context=/admin`, used to support http://127.0.0.1:18083/admin to configure the context, which can facilitate nginx proxy forwarding.

**Comment by Gilbert-Wong** [comment]
Hi, @mg0324 , we have no schedule to implement this feature, you could configure nginx to gain your ends.

**Comment by salcedo** [comment]
Configuring nginx, traefik, or any front-end to have the dashboard on a path /admin can be done. In order for this to work, we also need the ability to set a base root for all routes in the plugin, as @mg0324 initially mentioned.

I imagine this feature would be trivial to add, but I don't know Erlang. Any chance someone could revisit this?

**Comment by xeniumlee** [comment]
sed -i 's|/static/|static/|g' ./lib/emqx_dashboard-3.0/priv/www/index.html
sed -i 's|o.p="/"|o.p=""|g' ./lib/emqx_dashboard-3.0/priv/www/static/js/manifest.19803c394fb99afac0e4.js
sed -i 's|/static/|../|g' ./lib/emqx_dashboard-3.0/priv/www/static/css/app.22f05f31024b205fa95684c117d41d0d.css
sed -i 's|baseURL:"/api/v3"|baseURL:"{{ _baseURL_ }}/api/v3"|g' ./lib/emqx_dashboard-3.0/priv/www/static/js/app.20f9a02f303cbb0201f0.js
sed -i 's|this.uri="/api/v3"|this.uri="{{ _baseURL_ }}/api/v3"|g' ./lib/emqx_dashboard-3.0/priv/www/static/js/4.2296966a704524b5287c.js
