### ISSUE TITLE
Empty node dropdown since 4.0.3

### ISSUE THREAD

**Issue by fuji4** [emqx/emqx-dashboard#205]
In EMQX 4.0.3 the ndoe select dropdown in the upper right corner has empty values. There are still 2 entries (one for each node) but they are empty (see screenshot).

System: Ubuntu 18.04
EMQX: 4.0.3

![Clipboard01](https://user-images.githubusercontent.com/1442410/75445417-a69b8380-5965-11ea-909e-8c626bd67ce0.png)

**Comment by HJianBo** [comment]
Duplicated: https://github.com/emqx/emqx/issues/3278

And it seems fixed at https://github.com/emqx/emqx-dashboard/pull/206

**Comment by HJianBo** [comment]
The fix has released at 4.0.4. Thanks for your feedback :)
