### ISSUE TITLE
feature request: edit exiting rules

### ISSUE THREAD

**Issue by victorclaessen** [emqx/emqx-dashboard#229]
I was wondering if it would be possible to make it so that you could edit existing rules in the dashboard. It is a bit of a hassle while testing to have to delete a rule completely and make it again from scratch just to change one parameter.

**Comment by HJianBo** [comment]
Hi @victorclaessen Thank for your suggestion.

The feature has implemented in v4.1-beta.1. That will be released in these days

**Comment by HJianBo** [comment]
Hi @victorclaessen This feature has released at v4.1.0.

Thanks for your suggestion again :)
