### ISSUE TITLE
How to start Dashboar

### ISSUE THREAD

**Issue by UlissesZorzan** [emqx/emqx-dashboard#266]
I'm starting with EMQ and I've read the documentation a lot, but I'm not able to use the dashboard.

I installed version 4.2.1 for Centos 7.

The Broker works normally, I just can't use the Dashboard on port 18083 as described in the documentation

I checked if there was any process on that door and found nothing.

If anyone can help me I will be grateful!

**Comment by HJianBo** [comment]
It is possible that the port 18083 on your host is already occupied by another program, causing the emqx_dashboard plugin to fail to start.

**Comment by UlissesZorzan** [comment]
Apparently there is no process running on port 18083
Would I have any way to check the application log or try to start the Dashboard plugin manually

`[greenwave-xx@##]$ sudo lsof -w -n -i tcp:1883
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node      3056 root   24u  IPv4 188996      0t0  TCP 127.0.0.1:34826->127.0.0.1:ibm-mqisdp (ESTABLISHED)
beam.smp 32159 emqx   36u  IPv4 176264      0t0  TCP *:ibm-mqisdp (LISTEN)
beam.smp 32159 emqx   40u  IPv4 190208      0t0  TCP 127.0.0.1:ibm-mqisdp->127.0.0.1:34826 (ESTABLISHED)
[greenwave-xx@##]$ sudo lsof -w -n -i tcp:18083
[greenwave-xx@##$ sudo lsof -w -n -i udp:18083
[greenwave--xx@##]$
`



> É possível que a porta 18083 em seu host já esteja ocupada por outro programa, fazendo com que o plugin emqx_dashboard falhe ao iniciar.
