### ISSUE TITLE
Can I add more users ...

### ISSUE THREAD

**Issue by notjulian** [emqx/emqx-dashboard#268]
Hi, 
can I add more than one user via conf?

otherwise when I recreate the container I've to add them manually

thanks

**Comment by HJianBo** [comment]
Not yet.

Maybe you can use CLI/REST API to add a new user in some starting/initial script

**Comment by notjulian** [comment]
> Not yet.
> 
> Maybe you can use CLI/REST API to add a new user in some starting/initial script

thanks so much
