### ISSUE TITLE
Dashboard isn't saving modified configuration

### ISSUE THREAD

**Issue by armandokeller** [emqx/emqx-dashboard#27]
I've tried to edit the configurations of the emqx_auth_mongo plugin using the dashboard, and everything is working as expected after clicking the confirm button. 

But when I restart the emqx service, all the configuration data is lost and returned to the default configuration.

I've installed using the deb package on Ubuntu 18.4 on my local computer and on a vm.

**Comment by ysfscream** [comment]
Yes, this is normal, we will discuss this feature in the future. Thanks for your @armandokeller feedback.
