### ISSUE TITLE
Unable to setup default admin credentials using emqx.conf

### ISSUE THREAD

**Issue by aalexren** [emqx/emqx-dashboard#279]
I try to use settings from example:
```
dashboard.default_user.username = admin
dashboard.default_user.password = admin
```
But it gives me error:
> 2024-02-14T17:16:02.593079+03:00 [error] failed_to_check_schema: emqx_conf_schema
> 2024-02-14T17:16:02.595163+03:00 [error] #{reason => unknown_fields,path => "dashboard",unknown => "default_user",kind => validation_error,unmatched => "bootstrap_users_file,cors,..."}
> ERROR: call_hocon_failed: -v -s emqx_conf_schema -c /etc/emqx/emqx.conf check_schema

Steps to reproduce:
1. Install emqx using deb package: `https://www.emqx.com/en/downloads/broker/5.5.0/emqx-5.5.0-debian11-amd64.deb`
2. Edit conf (add those lines)
3. Run emqx

**Version**: EMQX 5.5.0
**Linux machine**: Linux dwh 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
**Distributor ID**: Debian
**Description**:    Debian GNU/Linux 12 (bookworm)
**Release**:        12
**Codename**:       bookworm

**Comment by id** [comment]
Hi @aalexren. Which example are you referring to?

**Comment by id** [comment]
Try this:

```
dashboard.default_username = admin
dashboard.default_password = admin
```

**Comment by aalexren** [comment]
@id Yeah, this works, thank you a lot! Sorry for such a delay!
