### ISSUE TITLE
Nginx reverse proxy to offload SSL for the dashboard

### ISSUE THREAD

**Issue by elcreator** [emqx/emqx-dashboard#280]
I'm using the next command to run EMQX:
```bash
/usr/bin/docker run --rm --name emqx -p 127.0.0.1:1883:1883 \
        -p 127.0.0.1:8083:8083 -p 127.0.0.1:8084:8084 -p 127.0.0.1:8883:8883 \
        -p 127.0.0.1:18083:18083 docker.io/emqx/emqx:latest
```

curl http://127.0.01:18083 gives me plain HTML.

Also I use the next Nginx reverse proxy config:
```nginx
upstream emqx_admin {
    server 127.0.0.1:18083;
}
server {
    server_name mqtt.site.com;

    if ($host != mqtt.site.com) {
        return 444;
    }

    access_log /home/mqtt-site-com/logs/admin-access.log;
    error_log /home/mqtt-site-com/logs/admin-error.log;

    location / {
       proxy_pass http://emqx_admin;
        include /etc/nginx/proxy_params;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
   }

    listen mqtt.site.com:18083 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mqtt.site.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mqtt.site.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```
It not works. curl http://mqtt.site.com:18083 returns plain HTML but curl https://mqtt.site.com:18083 of course not works as it receives plain HTML instead of certificate exchange.

**Comment by id** [comment]
@elcreator do both emqx and docker run on the same host? If yes, then I'm not sure how do they even work. 2 processes cannot both bind to 18083.
Try to replace `listen mqtt.site.com:18083 ssl;` with `listen mqtt.site.com:18084 ssl;` and `curl https://mqtt.site.com:18084/`

**Comment by elcreator** [comment]
Why shouldn't it? Network socket needs an unique pair of IP and port for
binding. Same port on different interfaces or different ports on the same
interface works fine.

**Comment by id** [comment]
what does `mqtt.site.com` resolve to?

**Comment by elcreator** [comment]
It resolves to server external IP like 98.76.54.32. Meanwhile I tried to change 127.0.0.1:18083:18083 to 127.0.0.1:18084:18083 so app in Docker listens to the same port 18083 as used on external interface 98.76.54.32:18083 and also made corresponding change in
```
upstream emqx_admin {
    server 127.0.0.1:18084;
}
```
It not works. I think I need to inject custom config to the Emqx in the docker container and change things like proxy.

**Comment by id** [comment]
Try this
```
upstream emqx_admin {
    server emqx:18083;
}
```

**Comment by id** [comment]
If `curl http://mqtt.site.com:18083/` returns plain HTML it means something is wrong with your nginx configuration. You don't have plain text HTTP listener on 18083 in nginx, only ssl one.

Try to first make nginx working as you expect. Return static json or html in `location /` instead of proxying it to emqx, and test if you can get it via https.

**Comment by elcreator** [comment]
It was a very strange bug on Hetzner. Even after stopping nginx, emqx and
checking via netstat that nothing is running on 18083 I still was able to
see the open port 18083 via nmap from outside and get plain html as before.

**Comment by elcreator** [comment]
Thank you for help, it works now.
