### ISSUE TITLE
Rename `/World` into `world` again

### ISSUE THREAD

**Issue by chimit** [emqx/emqx-dashboard#8]
Because it's a good practice not to use leading or trailing slashes in topic names. And also not to use uppercase.

![image](https://user-images.githubusercontent.com/839349/48816214-4722f100-ed7c-11e8-8417-7e2010a39cc0.png)

**Comment by Gilbert-Wong** [comment]
Sorry, we do not think it is a bad practice and we have no schedule to modify it.

**Comment by chimit** [comment]
@Gilbert-Wong https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

Furthermore, you already applied the same PR before: https://github.com/emqtt/emq-dashboard/pull/88

**Comment by linjunjj** [comment]
I'm working on it

**Comment by ysfscream** [comment]
Hi @chimit again. We have fixed it before, now the default topic is `testtopic/#`. Thanks.
