### ISSUE TITLE
Increase the number of items per page

### ISSUE THREAD

**Issue by chimit** [emqx/emqx-dashboard#9]
Connections, Sessions, Topics, Subscriptions pages display only 10 items per page. It's very inconvenient. Please, increase it to at least 30 items per page.

**Comment by ysfscream** [comment]
Hi, @chimit Thanks for your advice. Sorry late. Now you can choose `10 50 100 300 500` items per page. I will close this issue.

![image](https://user-images.githubusercontent.com/21299158/65016368-ae86de80-d956-11e9-9c42-837d9ce1efd6.png)
