### ISSUE TITLE
The default username & passwd can't login into console

### ISSUE THREAD

**Issue by MMichael-S** [emqx/emqx-dashboard#92]
Hi Experts

I used the AMAZON AMI to start "EMQ X 3.0.1 - CentOS 7"
https://aws.amazon.com/marketplace/pp/B07N2ZFVLX?qid=1552872864456&.

After the instance booted, I can ssh login and can see the services started by "netstat".
I can open dashboard console using 18083 port, but I can't login using the default username & passwd ---  admin/public.

Thanks for your suggestions.

**Comment by MMichael-S** [comment]
The error messages is "Unknown Error" .....  
: (

**Comment by MMichael-S** [comment]
I contact the EMQ support and get the information "Init password is EC2 instance_id" .
It works.
Thank you all.

**Comment by Gilbert-Wong** [comment]
Good 👍

**Comment by xyz361** [comment]
Sorry , some info is lost in AWS Usage Instructions. We will update it soon.
"Once the instance is running, user can log into the server, cd to the EMQ dir and check EMQ X status by running:
         ./bin/emqx_ctl status

emqx_dashboard is the web management console for the EMQ X broker, which is enabled by default. When EMQ X starts successfully, user can access it by visiting http://localhost:18083 with the username/password: admin/instance id."
